
name: CI Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t weather-app .

      - name: Run container test
        run: |
          docker run --rm -d -p 5000:5000 weather-app
          sleep 5
          curl -f http://localhost:5000
